# Generated by Django 4.1.5 on 2023-03-22 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('age', models.CharField(max_length=12)),
                ('ville', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_facture', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=3, max_digits=900)),
                ('dernier_modification', models.DateTimeField(blank=True, null=True)),
                ('statut', models.BooleanField(default=False)),
                ('type_facture', models.CharField(choices=[('R', 'Reçu'), ('P', 'Facture Proforma'), ('F', 'Facture')], max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('quantite', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=900)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.facture')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
