# Generated by Django 4.1.5 on 2023-03-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('Reçu', 'Reçu'), ('Proforma', 'Facture Proforma'), ('Facture', 'Facture')], max_length=100),
        ),
    ]
